import 'package:flutter/material.dart';

import '../models/level_visual_theme.dart';

class LevelVisualThemeService {
  const LevelVisualThemeService();

  static const themes = [
    LevelVisualTheme(
      levelId: 1,
      name: 'Холодный архив',
      modelCode: 'ARCHIVE-01',
      lockLabel: 'SEALED',
      accent: Color(0xFF67E8F9),
      start: Color(0xFF0F2638),
      end: Color(0xFF0B1018),
      pattern: SafePanelPattern.grid,
    ),
    LevelVisualTheme(
      levelId: 2,
      name: 'Пыльное стекло',
      modelCode: 'DUST-02',
      lockLabel: 'LOCKED',
      accent: Color(0xFFD7CCC8),
      start: Color(0xFF2B211B),
      end: Color(0xFF101010),
      pattern: SafePanelPattern.dotMatrix,
    ),
    LevelVisualTheme(
      levelId: 3,
      name: 'Нулевой контур',
      modelCode: 'ZERO-03',
      lockLabel: 'IDLE',
      accent: Color(0xFF7DD3FC),
      start: Color(0xFF102A43),
      end: Color(0xFF08111F),
      pattern: SafePanelPattern.rings,
    ),
    LevelVisualTheme(
      levelId: 4,
      name: 'Латунная рамка',
      modelCode: 'BRASS-04',
      lockLabel: 'SECURED',
      accent: Color(0xFFFFC857),
      start: Color(0xFF34270E),
      end: Color(0xFF111827),
      pattern: SafePanelPattern.diagonal,
    ),
    LevelVisualTheme(
      levelId: 5,
      name: 'Тихий коридор',
      modelCode: 'HALL-05',
      lockLabel: 'MUTED',
      accent: Color(0xFFA7F3D0),
      start: Color(0xFF113529),
      end: Color(0xFF07130F),
      pattern: SafePanelPattern.circuit,
    ),
    LevelVisualTheme(
      levelId: 6,
      name: 'Слабая лампа',
      modelCode: 'LAMP-06',
      lockLabel: 'DIM',
      accent: Color(0xFFFDE68A),
      start: Color(0xFF31280F),
      end: Color(0xFF14110A),
      pattern: SafePanelPattern.blueprint,
    ),
    LevelVisualTheme(
      levelId: 7,
      name: 'Северный металл',
      modelCode: 'NORTH-07',
      lockLabel: 'FROST',
      accent: Color(0xFF93C5FD),
      start: Color(0xFF14233E),
      end: Color(0xFF070B13),
      pattern: SafePanelPattern.rings,
    ),
    LevelVisualTheme(
      levelId: 8,
      name: 'Мокрый бетон',
      modelCode: 'CONC-08',
      lockLabel: 'DAMP',
      accent: Color(0xFF94A3B8),
      start: Color(0xFF202733),
      end: Color(0xFF0F1115),
      pattern: SafePanelPattern.dotMatrix,
    ),
    LevelVisualTheme(
      levelId: 9,
      name: 'Синяя подсветка',
      modelCode: 'BLUE-09',
      lockLabel: 'GLOW',
      accent: Color(0xFF5D8CFF),
      start: Color(0xFF111B46),
      end: Color(0xFF090C1A),
      pattern: SafePanelPattern.grid,
    ),
    LevelVisualTheme(
      levelId: 10,
      name: 'Красная папка',
      modelCode: 'RED-10',
      lockLabel: 'FILED',
      accent: Color(0xFFF87171),
      start: Color(0xFF3B1118),
      end: Color(0xFF12080A),
      pattern: SafePanelPattern.diagonal,
    ),
    LevelVisualTheme(
      levelId: 11,
      name: 'Стеклянная дверь',
      modelCode: 'GLASS-11',
      lockLabel: 'CLEAR',
      accent: Color(0xFFBAE6FD),
      start: Color(0xFF122B38),
      end: Color(0xFF07141A),
      pattern: SafePanelPattern.blueprint,
    ),
    LevelVisualTheme(
      levelId: 12,
      name: 'Комната хранения',
      modelCode: 'STORE-12',
      lockLabel: 'STORED',
      accent: Color(0xFF34D399),
      start: Color(0xFF123524),
      end: Color(0xFF07130C),
      pattern: SafePanelPattern.circuit,
    ),
    LevelVisualTheme(
      levelId: 13,
      name: 'Черная бирка',
      modelCode: 'TAG-13',
      lockLabel: 'BLACK',
      accent: Color(0xFFE5E7EB),
      start: Color(0xFF18181B),
      end: Color(0xFF050505),
      pattern: SafePanelPattern.rings,
    ),
    LevelVisualTheme(
      levelId: 14,
      name: 'Беззвучный лифт',
      modelCode: 'LIFT-14',
      lockLabel: 'SILENT',
      accent: Color(0xFFC4B5FD),
      start: Color(0xFF261B3D),
      end: Color(0xFF0E0A16),
      pattern: SafePanelPattern.dotMatrix,
    ),
    LevelVisualTheme(
      levelId: 15,
      name: 'Северный файл',
      modelCode: 'FILE-15',
      lockLabel: 'ASCEND',
      accent: Color(0xFF60A5FA),
      start: Color(0xFF102544),
      end: Color(0xFF070D18),
      pattern: SafePanelPattern.diagonal,
    ),
    LevelVisualTheme(
      levelId: 16,
      name: 'Пульт охраны',
      modelCode: 'GUARD-16',
      lockLabel: 'ARMED',
      accent: Color(0xFFFB923C),
      start: Color(0xFF3B1D0B),
      end: Color(0xFF130A05),
      pattern: SafePanelPattern.circuit,
    ),
    LevelVisualTheme(
      levelId: 17,
      name: 'Запертый стеллаж',
      modelCode: 'RACK-17',
      lockLabel: 'SHELF',
      accent: Color(0xFFCBD5E1),
      start: Color(0xFF242A33),
      end: Color(0xFF0B0E12),
      pattern: SafePanelPattern.grid,
    ),
    LevelVisualTheme(
      levelId: 18,
      name: 'Серый планшет',
      modelCode: 'SLATE-18',
      lockLabel: 'SLATE',
      accent: Color(0xFF9CA3AF),
      start: Color(0xFF25272C),
      end: Color(0xFF0D0E10),
      pattern: SafePanelPattern.blueprint,
    ),
    LevelVisualTheme(
      levelId: 19,
      name: 'Пятый контейнер',
      modelCode: 'CNTR-19',
      lockLabel: 'CARGO',
      accent: Color(0xFFF59E0B),
      start: Color(0xFF332207),
      end: Color(0xFF110C04),
      pattern: SafePanelPattern.diagonal,
    ),
    LevelVisualTheme(
      levelId: 20,
      name: 'Сейф с меткой',
      modelCode: 'MARK-20',
      lockLabel: 'TAGGED',
      accent: Color(0xFFFB7185),
      start: Color(0xFF3A1220),
      end: Color(0xFF12070C),
      pattern: SafePanelPattern.rings,
    ),
    LevelVisualTheme(
      levelId: 21,
      name: 'Двойной протокол',
      modelCode: 'PROTO-21',
      lockLabel: 'DUAL',
      accent: Color(0xFF22D3EE),
      start: Color(0xFF07313A),
      end: Color(0xFF051116),
      pattern: SafePanelPattern.circuit,
    ),
    LevelVisualTheme(
      levelId: 22,
      name: 'Зал отражений',
      modelCode: 'MIRR-22',
      lockLabel: 'REFLECT',
      accent: Color(0xFFDDD6FE),
      start: Color(0xFF2B2140),
      end: Color(0xFF0B0812),
      pattern: SafePanelPattern.blueprint,
    ),
    LevelVisualTheme(
      levelId: 23,
      name: 'Короткий импульс',
      modelCode: 'PULSE-23',
      lockLabel: 'SPIKE',
      accent: Color(0xFFEF4444),
      start: Color(0xFF3B0D0D),
      end: Color(0xFF120404),
      pattern: SafePanelPattern.dotMatrix,
    ),
    LevelVisualTheme(
      levelId: 24,
      name: 'Пять контактов',
      modelCode: 'PIN-24',
      lockLabel: 'FIVE',
      accent: Color(0xFF2DD4BF),
      start: Color(0xFF0C352F),
      end: Color(0xFF041210),
      pattern: SafePanelPattern.grid,
    ),
    LevelVisualTheme(
      levelId: 25,
      name: 'Узел питания',
      modelCode: 'POWER-25',
      lockLabel: 'LIVE',
      accent: Color(0xFFFACC15),
      start: Color(0xFF342E08),
      end: Color(0xFF121004),
      pattern: SafePanelPattern.circuit,
    ),
    LevelVisualTheme(
      levelId: 26,
      name: 'Складская метка',
      modelCode: 'DEPOT-26',
      lockLabel: 'WARE',
      accent: Color(0xFFFB923C),
      start: Color(0xFF3A220B),
      end: Color(0xFF120A04),
      pattern: SafePanelPattern.blueprint,
    ),
    LevelVisualTheme(
      levelId: 27,
      name: 'Глухой механизм',
      modelCode: 'MUTE-27',
      lockLabel: 'DEAF',
      accent: Color(0xFFA3E635),
      start: Color(0xFF24350B),
      end: Color(0xFF0B1204),
      pattern: SafePanelPattern.rings,
    ),
    LevelVisualTheme(
      levelId: 28,
      name: 'Темный дисплей',
      modelCode: 'DARK-28',
      lockLabel: 'NIGHT',
      accent: Color(0xFF818CF8),
      start: Color(0xFF191A3A),
      end: Color(0xFF070815),
      pattern: SafePanelPattern.diagonal,
    ),
    LevelVisualTheme(
      levelId: 29,
      name: 'Медная рамка',
      modelCode: 'COPR-29',
      lockLabel: 'COPPER',
      accent: Color(0xFFF97316),
      start: Color(0xFF3A1A08),
      end: Color(0xFF120804),
      pattern: SafePanelPattern.dotMatrix,
    ),
    LevelVisualTheme(
      levelId: 30,
      name: 'Последняя ячейка',
      modelCode: 'FINAL-30',
      lockLabel: 'FINAL',
      accent: Color(0xFF10B981),
      start: Color(0xFF093528),
      end: Color(0xFF020F0B),
      pattern: SafePanelPattern.circuit,
    ),
  ];

  LevelVisualTheme themeForLevel(int levelId) {
    return themes.firstWhere((theme) => theme.levelId == levelId);
  }
}
